development:
  adapter: postgresql
  encoding: utf8
  database: one_paste_development
  pool: 5
  username: nitish
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: one_paste_test
  pool: 5
  username: nitish
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: one_paste_production
  pool: 5
  username: nitish
  password:
